/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CatalogError = { 'categoryInUse' : null } |
  { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null } |
  { 'duplicateName' : null };
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'createdAt' : Timestamp,
}
export type CategoryId = bigint;
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'featured' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'available' : boolean,
  'updatedAt' : Timestamp,
  'price' : bigint,
  'images' : Array<ProductImage>,
}
export interface ProductFilter {
  'categoryId' : [] | [CategoryId],
  'sort' : [] | [ProductSort],
  'search' : [] | [string],
}
export type ProductId = bigint;
export interface ProductImage {
  'blob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
}
export interface ProductInput {
  'categoryId' : CategoryId,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'price' : bigint,
  'images' : Array<ProductImage>,
}
export type ProductSort = { 'priceLowToHigh' : null } |
  { 'newest' : null } |
  { 'priceHighToLow' : null };
export interface ProductUpdate {
  'categoryId' : [] | [CategoryId],
  'featured' : [] | [boolean],
  'name' : [] | [string],
  'description' : [] | [string],
  'available' : [] | [boolean],
  'price' : [] | [bigint],
  'images' : [] | [Array<ProductImage>],
}
export type Result = { 'ok' : StoreSettings } |
  { 'err' : CatalogError };
export type Result_1 = { 'ok' : Product } |
  { 'err' : CatalogError };
export type Result_2 = { 'ok' : Category } |
  { 'err' : CatalogError };
export type Result_3 = { 'ok' : null } |
  { 'err' : CatalogError };
export type Result_4 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface StoreSettings {
  'tagline' : string,
  'whatsappNumber' : string,
  'address' : string,
  'openingHours' : string,
  'shopName' : string,
  'phone' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_4>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string], Result_2>,
  'createProduct' : ActorMethod<[ProductInput], Result_1>,
  'deleteCategory' : ActorMethod<[CategoryId], Result_3>,
  'deleteProduct' : ActorMethod<[ProductId], Result_3>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Static Markdown description of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getStoreSettings' : ActorMethod<[], StoreSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'listRelatedProducts' : ActorMethod<[ProductId], Array<Product>>,
  'renameCategory' : ActorMethod<[CategoryId, string], Result_2>,
  'schema' : ActorMethod<[], string>,
  'setProductAvailability' : ActorMethod<[ProductId, boolean], Result_1>,
  'updateProduct' : ActorMethod<[ProductId, ProductUpdate], Result_1>,
  'updateStoreSettings' : ActorMethod<[StoreSettings], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];