/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const CatalogError = IDL.Variant({
  'categoryInUse' : IDL.Null,
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'duplicateName' : IDL.Null,
});
export const Result_2 = IDL.Variant({ 'ok' : Category, 'err' : CatalogError });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductImage = IDL.Record({
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const ProductInput = IDL.Record({
  'categoryId' : CategoryId,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ProductImage),
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'updatedAt' : Timestamp,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ProductImage),
});
export const Result_1 = IDL.Variant({ 'ok' : Product, 'err' : CatalogError });
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : CatalogError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const StoreSettings = IDL.Record({
  'tagline' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'shopName' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductSort = IDL.Variant({
  'priceLowToHigh' : IDL.Null,
  'newest' : IDL.Null,
  'priceHighToLow' : IDL.Null,
});
export const ProductFilter = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'sort' : IDL.Opt(ProductSort),
  'search' : IDL.Opt(IDL.Text),
});
export const ProductUpdate = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'featured' : IDL.Opt(IDL.Bool),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'available' : IDL.Opt(IDL.Bool),
  'price' : IDL.Opt(IDL.Nat),
  'images' : IDL.Opt(IDL.Vec(ProductImage)),
});
export const Result = IDL.Variant({
  'ok' : StoreSettings,
  'err' : CatalogError,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_4], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [Result_2], []),
  'createProduct' : IDL.Func([ProductInput], [Result_1], []),
  'deleteCategory' : IDL.Func([CategoryId], [Result_3], []),
  'deleteProduct' : IDL.Func([ProductId], [Result_3], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'listRelatedProducts' : IDL.Func([ProductId], [IDL.Vec(Product)], ['query']),
  'renameCategory' : IDL.Func([CategoryId, IDL.Text], [Result_2], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setProductAvailability' : IDL.Func([ProductId, IDL.Bool], [Result_1], []),
  'updateProduct' : IDL.Func([ProductId, ProductUpdate], [Result_1], []),
  'updateStoreSettings' : IDL.Func([StoreSettings], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const CatalogError = IDL.Variant({
    'categoryInUse' : IDL.Null,
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'duplicateName' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : Category, 'err' : CatalogError });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductImage = IDL.Record({
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const ProductInput = IDL.Record({
    'categoryId' : CategoryId,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ProductImage),
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'updatedAt' : Timestamp,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ProductImage),
  });
  const Result_1 = IDL.Variant({ 'ok' : Product, 'err' : CatalogError });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : CatalogError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const StoreSettings = IDL.Record({
    'tagline' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'shopName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductSort = IDL.Variant({
    'priceLowToHigh' : IDL.Null,
    'newest' : IDL.Null,
    'priceHighToLow' : IDL.Null,
  });
  const ProductFilter = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'sort' : IDL.Opt(ProductSort),
    'search' : IDL.Opt(IDL.Text),
  });
  const ProductUpdate = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'featured' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'available' : IDL.Opt(IDL.Bool),
    'price' : IDL.Opt(IDL.Nat),
    'images' : IDL.Opt(IDL.Vec(ProductImage)),
  });
  const Result = IDL.Variant({ 'ok' : StoreSettings, 'err' : CatalogError });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_4], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [Result_2], []),
    'createProduct' : IDL.Func([ProductInput], [Result_1], []),
    'deleteCategory' : IDL.Func([CategoryId], [Result_3], []),
    'deleteProduct' : IDL.Func([ProductId], [Result_3], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'listRelatedProducts' : IDL.Func(
        [ProductId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'renameCategory' : IDL.Func([CategoryId, IDL.Text], [Result_2], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setProductAvailability' : IDL.Func([ProductId, IDL.Bool], [Result_1], []),
    'updateProduct' : IDL.Func([ProductId, ProductUpdate], [Result_1], []),
    'updateStoreSettings' : IDL.Func([StoreSettings], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };